package dto

type GetGlobalSettingsRequest struct {
	ID int64 `form:"id" json:"id"  binding:"required"`
}

type GetGlobalSettingsResponse struct {
	ID                        int64          `form:"id" json:"id"`
	ChatAIEnabled             bool           `form:"chat_ai_enabled" json:"chat_ai_enabled"`
	ChatAITrigger             string         `form:"chat_ai_trigger" json:"chat_ai_trigger"`
	ChatBaseURL               string         `form:"chat_base_url" json:"chat_base_url"`
	ChatAPIKey                string         `form:"chat_api_key" json:"chat_api_key"`
	ChatModel                 string         `form:"chat_model" json:"chat_model"`
	ImageRecognitionModel     string         `form:"image_recognition_model" json:"image_recognition_model"`
	ChatPrompt                string         `form:"chat_prompt" json:"chat_prompt"`
	MaxCompletionTokens       int            `form:"max_completion_tokens" json:"max_completion_tokens"`
	ImageAIEnabled            bool           `form:"image_ai_enabled" json:"image_ai_enabled"`
	ImageAISettings           map[string]any `form:"image_ai_settings" json:"image_ai_settings"`
	TTSEnabled                bool           `form:"tts_enabled" json:"tts_enabled"`
	TTSModel                  string         `form:"tts_model" json:"tts_model"`
	TTSSettings               map[string]any `form:"tts_settings" json:"tts_settings"`
	WelcomeEnabled            bool           `form:"welcome_enabled" json:"welcome_enabled"`
	WelcomeType               string         `form:"welcome_type" json:"welcome_type"`
	WelcomeText               string         `form:"welcome_text" json:"welcome_text"`
	WelcomeEmojiMD5           string         `form:"welcome_emoji_md5" json:"welcome_emoji_md5"`
	WelcomeEmojiLen           int64          `form:"welcome_emoji_len" json:"welcome_emoji_len"`
	WelcomeImageURL           string         `form:"welcome_image_url" json:"welcome_image_url"`
	WelcomeURL                string         `form:"welcome_url" json:"welcome_url"`
	PatEnabled                bool           `form:"pat_enabled" json:"pat_enabled"`
	PatType                   string         `form:"pat_type" json:"pat_type"`
	PatText                   string         `form:"pat_text" json:"pat_text"`
	PatVoiceTimbre            string         `form:"pat_voice_timbre" json:"pat_voice_timbre"`
	LeaveChatRoomAlertEnabled bool           `form:"leave_chat_room_alert_enabled" json:"leave_chat_room_alert_enabled"`
	LeaveChatRoomAlertText    string         `form:"leave_chat_room_alert_text" json:"leave_chat_room_alert_text"`
	ChatRoomRankingEnabled    bool           `form:"chat_room_ranking_enabled" json:"chat_room_ranking_enabled"`
	ChatRoomRankingDailyCron  string         `form:"chat_room_ranking_daily_cron" json:"chat_room_ranking_daily_cron"`
	ChatRoomRankingWeeklyCron string         `form:"chat_room_ranking_weekly_cron" json:"chat_room_ranking_weekly_cron"`
	ChatRoomRankingMonthCron  string         `form:"chat_room_ranking_month_cron" json:"chat_room_ranking_month_cron"`
	ChatRoomSummaryEnabled    bool           `form:"chat_room_summary_enabled" json:"chat_room_summary_enabled"`
	ChatRoomSummaryModel      string         `form:"chat_room_summary_model" json:"chat_room_summary_model"`
	ChatRoomSummaryMode       string         `form:"chat_room_summary_mode" json:"chat_room_summary_mode"`
	ChatRoomSummaryCron       string         `form:"chat_room_summary_cron" json:"chat_room_summary_cron"`
	ChatRoomSummaryMinMessages *int           `form:"chat_room_summary_min_messages" json:"chat_room_summary_min_messages"`
	ChatRoomSummaryTriggerKeywords string      `form:"chat_room_summary_trigger_keywords" json:"chat_room_summary_trigger_keywords"`
	ChatRoomSummaryWindowHours *int           `form:"chat_room_summary_window_hours" json:"chat_room_summary_window_hours"`
	MediaExtractKeywords      string         `form:"media_extract_keywords" json:"media_extract_keywords"`
	MediaEvaluateKeywords     string         `form:"media_evaluate_keywords" json:"media_evaluate_keywords"`
	MediaExtractFailText      string         `form:"media_extract_fail_text" json:"media_extract_fail_text"`
	MediaRecognizeFailText    string         `form:"media_recognize_fail_text" json:"media_recognize_fail_text"`
	MediaRecognizeEmptyText   string         `form:"media_recognize_empty_text" json:"media_recognize_empty_text"`
	NewsEnabled               bool           `form:"news_enabled" json:"news_enabled"`
	NewsType                  string         `form:"news_type" json:"news_type"`
	NewsCron                  string         `form:"news_cron" json:"news_cron"`
	MorningEnabled            bool           `form:"morning_enabled" json:"morning_enabled"`
	MorningCron               string         `form:"morning_cron" json:"morning_cron"`
	FriendSyncCron            string         `form:"friend_sync_cron" json:"friend_sync_cron"`
	MemoryEnabled             bool           `form:"memory_enabled" json:"memory_enabled"`
	TextEmbeddingDimension    int            `form:"text_embedding_dimension" json:"text_embedding_dimension"`
	TextEmbeddingModel        string         `form:"text_embedding_model" json:"text_embedding_model"`
	ImageEmbeddingModel       string         `form:"image_embedding_model" json:"image_embedding_model"`
	ImageEmbeddingBaseURL     string         `form:"image_embedding_base_url" json:"image_embedding_base_url"`
	ImageEmbeddingAPIKey      string         `form:"image_embedding_api_key" json:"image_embedding_api_key"`
	ImageEmbeddingDimension   int            `form:"image_embedding_dimension" json:"image_embedding_dimension"`
}

type SaveGlobalSettingsRequest struct {
	ID                        int64          `form:"id" json:"id"  binding:"required"`
	ChatAIEnabled             bool           `form:"chat_ai_enabled" json:"chat_ai_enabled"`
	ChatAITrigger             string         `form:"chat_ai_trigger" json:"chat_ai_trigger"`
	ChatBaseURL               string         `form:"chat_base_url" json:"chat_base_url"`
	ChatAPIKey                string         `form:"chat_api_key" json:"chat_api_key"`
	ChatModel                 string         `form:"chat_model" json:"chat_model"`
	ImageRecognitionModel     string         `form:"image_recognition_model" json:"image_recognition_model"`
	ChatPrompt                string         `form:"chat_prompt" json:"chat_prompt"`
	MaxCompletionTokens       int            `form:"max_completion_tokens" json:"max_completion_tokens"`
	ImageAIEnabled            bool           `form:"image_ai_enabled" json:"image_ai_enabled"`
	ImageAISettings           map[string]any `form:"image_ai_settings" json:"image_ai_settings"`
	TTSEnabled                bool           `form:"tts_enabled" json:"tts_enabled"`
	TTSModel                  string         `form:"tts_model" json:"tts_model"`
	TTSSettings               map[string]any `form:"tts_settings" json:"tts_settings"`
	WelcomeEnabled            bool           `form:"welcome_enabled" json:"welcome_enabled"`
	WelcomeType               string         `form:"welcome_type" json:"welcome_type"`
	WelcomeText               string         `form:"welcome_text" json:"welcome_text"`
	WelcomeEmojiMD5           string         `form:"welcome_emoji_md5" json:"welcome_emoji_md5"`
	WelcomeEmojiLen           int64          `form:"welcome_emoji_len" json:"welcome_emoji_len"`
	WelcomeImageURL           string         `form:"welcome_image_url" json:"welcome_image_url"`
	WelcomeURL                string         `form:"welcome_url" json:"welcome_url"`
	PatEnabled                bool           `form:"pat_enabled" json:"pat_enabled"`
	PatType                   string         `form:"pat_type" json:"pat_type"`
	PatText                   string         `form:"pat_text" json:"pat_text"`
	PatVoiceTimbre            string         `form:"pat_voice_timbre" json:"pat_voice_timbre"`
	LeaveChatRoomAlertEnabled bool           `form:"leave_chat_room_alert_enabled" json:"leave_chat_room_alert_enabled"`
	LeaveChatRoomAlertText    string         `form:"leave_chat_room_alert_text" json:"leave_chat_room_alert_text"`
	ChatRoomRankingEnabled    bool           `form:"chat_room_ranking_enabled" json:"chat_room_ranking_enabled"`
	ChatRoomRankingDailyCron  string         `form:"chat_room_ranking_daily_cron" json:"chat_room_ranking_daily_cron"`
	ChatRoomRankingWeeklyCron string         `form:"chat_room_ranking_weekly_cron" json:"chat_room_ranking_weekly_cron"`
	ChatRoomRankingMonthCron  string         `form:"chat_room_ranking_month_cron" json:"chat_room_ranking_month_cron"`
	ChatRoomSummaryEnabled    bool           `form:"chat_room_summary_enabled" json:"chat_room_summary_enabled"`
	ChatRoomSummaryModel      string         `form:"chat_room_summary_model" json:"chat_room_summary_model"`
	ChatRoomSummaryMode       string         `form:"chat_room_summary_mode" json:"chat_room_summary_mode"`
	ChatRoomSummaryCron       string         `form:"chat_room_summary_cron" json:"chat_room_summary_cron"`
	ChatRoomSummaryMinMessages *int          `form:"chat_room_summary_min_messages" json:"chat_room_summary_min_messages"`
	ChatRoomSummaryTriggerKeywords string    `form:"chat_room_summary_trigger_keywords" json:"chat_room_summary_trigger_keywords"`
	ChatRoomSummaryWindowHours *int         `form:"chat_room_summary_window_hours" json:"chat_room_summary_window_hours"`
	MediaExtractKeywords      string         `form:"media_extract_keywords" json:"media_extract_keywords"`
	MediaEvaluateKeywords     string         `form:"media_evaluate_keywords" json:"media_evaluate_keywords"`
	MediaExtractFailText      string         `form:"media_extract_fail_text" json:"media_extract_fail_text"`
	MediaRecognizeFailText    string         `form:"media_recognize_fail_text" json:"media_recognize_fail_text"`
	MediaRecognizeEmptyText   string         `form:"media_recognize_empty_text" json:"media_recognize_empty_text"`
	NewsEnabled               bool           `form:"news_enabled" json:"news_enabled"`
	NewsType                  string         `form:"news_type" json:"news_type"`
	NewsCron                  string         `form:"news_cron" json:"news_cron"`
	MorningEnabled            bool           `form:"morning_enabled" json:"morning_enabled"`
	MorningCron               string         `form:"morning_cron" json:"morning_cron"`
	FriendSyncCron            string         `form:"friend_sync_cron" json:"friend_sync_cron"`
	MemoryEnabled             bool           `form:"memory_enabled" json:"memory_enabled"`
	TextEmbeddingModel        string         `form:"text_embedding_model" json:"text_embedding_model"`
	TextEmbeddingDimension    int            `form:"text_embedding_dimension" json:"text_embedding_dimension"`
	ImageEmbeddingModel       string         `form:"image_embedding_model" json:"image_embedding_model"`
	ImageEmbeddingBaseURL     string         `form:"image_embedding_base_url" json:"image_embedding_base_url"`
	ImageEmbeddingAPIKey      string         `form:"image_embedding_api_key" json:"image_embedding_api_key"`
	ImageEmbeddingDimension   int            `form:"image_embedding_dimension" json:"image_embedding_dimension"`
}
